directories:
  output: dist-electron
  buildResources: grid-system/frontend/public
appId: com.thadosoft.caller
productName: ThadoSoftCaller
win:
  target: nsis
  icon: grid-system/frontend/public/favicon.ico
files:
  - filter:
      - grid-system/frontend/dist/**/*
      - grid-system/backend/**/*
      - grid-system/frontend/electron/main.cjs
      - grid-system/frontend/electron/preload.js
extraResources:
  - from: grid-system/backend/
    to: backend/
    filter:
      - '**/*'
electronVersion: 25.0.0
